
trigger: none
pr: none

jobs:
- job: "Azure_Cost_Insights"
  timeoutInMinutes: 120  
  pool: "Hosted Ubuntu 1604"

  steps:
  
  - task: frezende.AzureCostInsights-Dev.AzureCostInsightsWidget.DownloadTask.DownloadCostData@1
    displayName: 'Download cost data - Kees Prive'
    inputs:
      ConnectedServiceNameARM: 'e3454697-f8ad-4681-8b6d-717c25d12e41' 
      apiToUse: usage
      currency: EUR
      locale: 'pt-br'
      regioInfo: BR 

  - task: frezende.AzureCostInsights-Dev.AzureCostInsightsWidget.DownloadTask.DownloadCostData@1
    displayName: 'Download Cost Data'
    inputs:
      ConnectedServiceNameARM: 'e3454697-f8ad-4681-8b6d-717c25d12e41'
  
  - task: frezende.AzureCostInsights-Dev.AzureCostInsightsWidget.PublishTask.PublishCostData@1
    displayName: 'Publish Cost Data'
    continueOnError: true

